In [1]:
%reset -fs

In [13]:
import pandas as pd
import numpy as np
import string
import re
from nltk.tokenize import word_tokenize
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

In [14]:
df = pd.read_csv('sotu_texts.csv')
df

,President,Year,Title,Text
0,George Washington,1790,First State of the Union Address,['I embrace with great satisfaction the opport...
1,George Washington,1790,Second State of the Union Address,['Fellow-Citizens of the Senate and the House ...
2,George Washington,1791,Third State of the Union Address,['Fellow-Citizens of the Senate and the House ...
3,George Washington,1792,Fourth State of the Union Address,['Fellow-Citizens of the Senate and of the Hou...
4,George Washington,1793,Fifth State of the Union Address,['Fellow Citizens of the Senate and of the Hou...
...,...,...,...,...
215,Barack Obama,2016,Barack Obama's Eighth State of the Union Address,"['Mr. Speaker, Mr. Vice President, Members of ..."
216,Donald Trump,2017,Donald Trump's First State of the Union Address,"['Mr. Speaker, Mr. Vice President, Members of ..."
217,Donald Trump,2018,Donald Trump's Second State of the Union Address,"['Mr. Speaker, Mr. Vice President, Members of ..."
218,Donald Trump,2019,Donald Trump's Third State of the Union Address,"['Madam Speaker, Mr. Vice President, Members o..."
219,Joe Biden,2022,Joe Biden's First State of The Union Address,"['Madam Speaker, Madam Vice President, our Fir..."

In [15]:
alphanumeric = lambda x: re.sub('\w*\d\w*', ' ', x)
punc_lower = lambda x: re.sub('[%s]' % re.escape(string.punctuation), ' ', x.lower())

df['Text'] = df.Text.map(alphanumeric).map(punc_lower)
df.head()

,President,Year,Title,Text
0,George Washington,1790,First State of the Union Address,i embrace with great satisfaction the opport...
1,George Washington,1790,Second State of the Union Address,fellow citizens of the senate and the house ...
2,George Washington,1791,Third State of the Union Address,fellow citizens of the senate and the house ...
3,George Washington,1792,Fourth State of the Union Address,fellow citizens of the senate and of the hou...
4,George Washington,1793,Fifth State of the Union Address,fellow citizens of the senate and of the hou...